# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Praetor < Formula
  desc "Terminal-based game client for The Eternal City"
  homepage "https://github.com/cyber-godzilla/praetor"
  version "0.0.15"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cyber-godzilla/praetor/releases/download/v0.0.15/praetor_0.0.15_darwin_amd64.tar.gz"
      sha256 "700bf3ad1fb97a9562f3d43749428c7665dcfa21ac7d846e0c642d62032bdb68"

      define_method(:install) do
        bin.install "praetor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cyber-godzilla/praetor/releases/download/v0.0.15/praetor_0.0.15_darwin_arm64.tar.gz"
      sha256 "c4f8272f836cfb52e8f3ff616aa9cc17cbc46220ada2525c52534f967cfb2869"

      define_method(:install) do
        bin.install "praetor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cyber-godzilla/praetor/releases/download/v0.0.15/praetor_0.0.15_linux_amd64.tar.gz"
      sha256 "8be945ac00c5fbe2acda3a62a286fd253a9b9915397507daf88b6d7de1c39002"
      define_method(:install) do
        bin.install "praetor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cyber-godzilla/praetor/releases/download/v0.0.15/praetor_0.0.15_linux_arm64.tar.gz"
      sha256 "d1a30e8a3b200b261cf691e531372ea4d8ad6a657d08755f929ad7a6f35be4b3"
      define_method(:install) do
        bin.install "praetor"
      end
    end
  end
end
